---
title: "R-Matrices"
author: "Carmen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Create matrices in R.
### Add values.

```{r}
# Make a sequence of values from 1 - 10 ----
my_values <- seq(from = 1, to = 10, by = 1)

# Look at it (always) ----
my_values
```

### Convert to matrix.

```{r}
# Convert to matrix ----
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE) #default fill by column, byrow = TRUE fills by row

# Check it out ----
class(my_matrix)
```

## Math with matrices.

```{r}
4 * my_matrix
```

```{r}
# Make 2x5 matrix ----
my_values2 <- seq(from = 21, to = 30, by = 1)
my_matrix2 <- matrix(my_values2, nrow = 2, byrow = TRUE)

# Check it out ----
my_matrix2
```

```{r}
my_matrix + my_matrix2
my_matrix2 - my_matrix
```

# Practice

```{r}
# Make a couple of 2x2 matrices ----
cats <- matrix(data = c(0,4,3,1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = TRUE)

# Look at them ----
cats
dogs

# find the dot product ----
cats %*% dogs
```

## Leslie Matrix Example

```{r}
# Create your matrix ----
insect_leslie <- matrix(c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), nrow = 3, ncol = 3, byrow = TRUE)

# Check it out ----
insect_leslie
```

```{r}
# Insect lifestage populations (year 0) ----
insect_y0 <- c(12000, 700, 500)
```

```{r}
# Populations at year 1 ----
insect_y1 <- insect_leslie %*% insect_y0

# Check it out ----
insect_y1 
```

```{r}
# Populations by lifestage at year 2 ----
insect_y2 <- insect_leslie %*% insect_y1

# Check it out ----
insect_y2
```

```{r}
# Populations by lifestage at year 3 ----
insect_y3 <- insect_leslie %*% insect_y2

# Check it out ----
insect_y3
```

## Practice for loops...

```{r}
years <- seq(from = 1, to = 10, by = 1)
insect_y0 <- c(12000, 700, 500)

x <- insect_leslie %*% insect_y0   
for(year in years) {
  x <- insect_leslie %*% x
  print(x)
}
```


```{r}
tree_leslie <- matrix(data = c(0, 0, 5000, 0.1, 0, 0, 0, 0.06, 0.95), 
                      nrow = 3, 
                      ncol = 3, 
                      byrow = TRUE)
tree_leslie

tree_y0 <- c(5000, 0, 0)

tree_y1 <- tree_leslie %*% tree_y0
tree_y1

tree_y2 <- tree_leslie %*% tree_y1
tree_y2
```

